### ISSUE TITLE
put link to digitool behind image in "Object bewerken" screen

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_crkc#10]
When you hover over an image in the CollectiveAccess "Object bewerken"  screen on the left hand side, a hand appears. But when clicking on the image nothing happens. 
CRKC would like to be able to click on the image and be directed immediately to an image in Digitool. Now they first have to go to the media tab to do that. 

Activate the link.

![image selection](https://f.cloud.github.com/assets/3798589/1254404/7f1b5e7c-2b75-11e3-88f1-0b779b938374.png)

**Comment by roxannewyns** [comment]
Vraag i.v.m. vraag en aanbod. 
Nu krijgen gebruikers die enkel toegang hebben tot de samenvatting slechts een kleine foto te zien. 
Een andere optie is de media toevoegen aan de samenvatting

**Comment by aruijmen** [comment]
Done
AND switched the lias-resolver to the libis-resolver

I need to update the necessary files here
- app/controllers/lookup/DigitoolController.php
- app/helpers/digitoolHelpers.php
- app/helpers/displayHelpers.php
- app/lib/ca/Attributes/Values/DigitoolUrlAttributeValues.php
- js/digitool/digitool.js
(updates were done on crkcsandbox_test)
