### ISSUE TITLE
Indexing problems - object records deleted from a set or collection still appear in the search results

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_crkc#12]
When an object record that was part of a "set" or a "collection" is removed of the "set" or "collection", it still remains visible in the search results for a longer period of time (sometimes up to 2 weeks or more, difficult to say) before finally disappearing from the search results.

This gives a discrepancy in the number of search results and what is actually attached to the set or the collection. E.g.

A search on object records part of the set "vraagenaanbod" (set_id 2) gives 481 results. 

![vraagenaanbod_set_zoekopdracht](https://f.cloud.github.com/assets/3798589/1623552/40d37f62-56b5-11e3-8314-de57cd9c6151.JPG)

When checking the set "vraagenaanbod" it shows that only 404 object records are assigned to this set. 
 
![vraagenaanbod_set_setmanager](https://f.cloud.github.com/assets/3798589/1623598/af9d7ede-56b5-11e3-8f65-8f6d56c10ddc.JPG)

The database gives 405 results for "vraagenaanbod" or "set_id 2", no idea where the difference of 1 is coming from. 

![vraagenaanbod_set_resultdatabase](https://f.cloud.github.com/assets/3798589/1623615/eab04f42-56b5-11e3-8d3b-9b711b872328.JPG)

The same happens for collections, where record no longer part of the collection keep appearing when you search on object belonging to a collection. It's not related to the cookies. I've done a test + deleted my cookies and the same happened. 

I've added "object_id/140995" to the set "testset".

![test_set_komfoor1](https://f.cloud.github.com/assets/3798589/1623817/d443df46-56b8-11e3-93dd-cd558a84d66a.JPG)

I've looked it up and it appeared in the results

![test_set_komfoor1](https://f.cloud.github.com/assets/3798589/1623823/e5fe50c2-56b8-11e3-84b4-05e6a81ee081.JPG)

After deleting the record "object_id/140995" from the set "testset", it still keeps appearing in the search results even though it is properly deleted.

![set_komfoor removed](https://f.cloud.github.com/assets/3798589/1623843/128f2c06-56b9-11e3-8d3d-88876bfd2e61.JPG)

![test_set_komfoor2](https://f.cloud.github.com/assets/3798589/1623855/56d03022-56b9-11e3-9fc0-316f33bcf66d.JPG)

**Comment by roxannewyns** [comment]
@naeemmuhammad 

Discrepancy in number of objects in set and number of objects when you search on the set in Find > Objecten:

set:"komfoor" has 53 objects in set, but when searching on the set via Find > Objects you only have 52 objects as a result

set:"twee_vazen" has 151 objects in set, but when searching on the set via Find > Objects you only have 148 objects as a result

set:"parochie_heilige" has 84 objects in set, but when searching on the set via Find > Objects you only have 62 objects as a result
![capture1](https://cloud.githubusercontent.com/assets/3798589/6373862/a00af6c6-bd0d-11e4-82c0-64ed883c519e.JPG)
![capture](https://cloud.githubusercontent.com/assets/3798589/6373891/bf21d16a-bd0d-11e4-873b-0b9db3fd06b3.JPG)
set:"maria" has 60 objects in set, but when searching on the set via Find > Objects you only have 58 objects as a result
![capture](https://cloud.githubusercontent.com/assets/3798589/6373957/26693264-bd0e-11e4-963c-8a5d1e6e6985.JPG)
![capture](https://cloud.githubusercontent.com/assets/3798589/6373971/311fb9d0-bd0e-11e4-91ad-205a90bb0b0d.JPG)

**Comment by roxannewyns** [comment]
@naeemmuhammad 
Discrepancy seems to occur from the start, so when first adding objects to a new set and then searching on the set via Vind > Objecten. 
So far I didn't have problems with removing objects from an existing set. When removing for example 5 items from a set on set level, there are 5 items less in the search results on that set as well. 
Also adding items to an existing set seems to work well.

**Comment by roxannewyns** [comment]
problem remains. e.g. 64 items added to set 'glas_in_lood' and when searching on the set you only get 11 results

**Comment by naeemmuhammad** [comment]
For the problem that you have described above we have the following details about the proposed solution:

A brief technical insight into the problem:
Currently, collective access indexer does not update indexing information of related rows of a record. For example, in case of removing an item from a set, index needs to be updated for related rows in tables ca_sets and ca_objects. That means , to exclude these rows from the new information that is to be sent to the indexing server .

Solution:
For this particular issue we need to make sure that related rows are not reindexed when we remove an item from a set. To achieve this we prepare a list (exclusion list) of such items that should be skipped while reindexing. Afterwards we use this list to check if the record that we are going to index exists in the exclusion list, if it exists we remove it from the data that is to be sent to the indexing server.

**Comment by roxannewyns** [comment]
Partner has tested, results are ok. Fix can be implemented in production. Reindexing needs to be planned on a good day so there is minimum encumbrance for the partner (e.g. a Friday evening).

**Comment by roxannewyns** [comment]
one remark from partner: when adding items to the set via Manage > My sets it takes a long time. Might be because of the size of the set (ca. 360 items) and the fact that they all are reindexed when saving the set.

**Comment by naeemmuhammad** [comment]
Indeed it takes more time when changes are made in the set visa set manager. That is because a lot of information needs to be reindexed every time we make changes in sets. If this is a potential issue we can work on it to find a fix.

**Comment by naeemmuhammad** [comment]
I have adapted the source code on production to implement this fix.

**Comment by naeemmuhammad** [comment]
The issue has been fixed. Now users can add and delete items from sets correctly. Search results for sets are consist with the number of items items shown in set manager.

**Comment by roxannewyns** [comment]
Probleem duikt terug op
Dringend te testen

**Comment by naeemmuhammad** [comment]
We have a separate issue (https://github.com/libis/ca_crkc/issues/59) for collections.
