### ISSUE TITLE
Test: Solr searching tests

### ISSUE THREAD

**Issue by samalloing** [libis/ca_crkc#17]
Data gets prepared by CollectiveAccess and is send to Solr,this should be tested as well:
* are Dates send properly to Solr (see #14)
* special fields like created and modified date are send to solr and should be searchable (see #16)
* the value of type_id should be correct (the value for search and indexing should be the same)
* values inside container should be searchable.
* advanced search queries get build by combining multiple fields. The fields must be combined properly like Solr expects and should give the correct result

**Comment by roxannewyns** [comment]
can be closed since we no longer use solr
