### ISSUE TITLE
pdf export : keep worker liver and document in case of fall out

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_crkc#38]
assigned @naeemmuhammad 

worker stops running. CRKC did not receive exported PDF (though they did receive the essage that an email would be send, so html was generated)

- keep worker running/live
- document how to restart the worker

**Comment by naeemmuhammad** [comment]
All workers will restart automatically if ICTS restart their server (that resides work scripts). In our new approach these workers will run as a Linux service that will start at the system startup. 

We are transferring all Collective Access systems to a new server, while transferring these systems their corresponding worker will be converted into Linux service. At the moment only Libisin Worker for Babteksts is being run as service as only Babtekst Collective Access was moved to the new server.

Note that workers will not restart themselves if ICTS’ RabbitMQ server goes down. In that scenario, worker will lose connection to RabbitMQ server, and will stop working. In this case workers need to be restarted by using standard Linux service start command after establishing that ICTS has brought the RabbitMQ server up again.

Documentation about the RabbitMQ workers is available in teamwork at ‘ Heron -> RabbitMQ Workers’ Page
