### ISSUE TITLE
role aanpassen voor alle PA. groepen

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_crkc#47]
Alle groepen die starten met 'PA.' moeten de rol "Raadpleger" (role_id/10) krijgen. Ze mogen geen andere rollen meer hebben.

**Comment by aruijmen** [comment]
Heb dit snel in MySQL gedaan. Hopelijk heb ik er niet teveel aangepast!

UPDATE ca_groups_x_roles 
SET role_id = 10 
where group_id in (select group_id from ca_user_groups where upper(name) like 'PA%') 
and role_id != 10
