### ISSUE TITLE
no results for list browsing (sandbox_test) 

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_crkc#49]
assigned @naeemmuhammad 
cc @aruijmen 

There seems to be something wrong with the list or relationship browsing in the sandbox. If you want to add an object name or a related collection, you get a blank list as results. 

![capture1](https://cloud.githubusercontent.com/assets/3798589/8033425/7edf4c3c-0dde-11e5-82c5-148d2784939c.JPG)

I just added some access points to the search indexing conf file, though I don't think this caused the problem. Removed them again to be sure of it

![capture](https://cloud.githubusercontent.com/assets/3798589/8033442/a7df3d22-0dde-11e5-8902-e2b9583c70b8.JPG)

related #48

**Comment by naeemmuhammad** [comment]
Php could not interpret double quotes used in display helpers file correctly. The issue has been fixed. However, i will make a fresh deployment (via github) to have an updated copy.
