### ISSUE TITLE
search issue on field inventarisator

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_crkc#50]
No search result or blank page when searching on the field 'inventarisator'
search queries are:
Dyck
Dyck*
Dyck, Annemie van

![capture](https://cloud.githubusercontent.com/assets/3798589/8034875/49675ee2-0dec-11e5-92a2-44d2c0b888b0.JPG)

Possibly an issue with [15-Jan-2015 10:49:18] Call to undefined method Zend_Search_Lucene_Search_Query_Phrase::getTerm() in ca_crkc/app/lib/core/Plugins/SearchEngine/Solr.php on line 287

**Comment by naeemmuhammad** [comment]
Fix: https://github.com/libis/providencesandbox/commit/c538600c9791c036347f61fa98e792201546a375

**Comment by roxannewyns** [comment]
Search with asterisk and multiple words gives no result (de munck*). 
Just one word with asteriks (munck*) works fine.
One or multiple words without asteriks works as well ('munck' or 'g de munck').

Perhaps this is normal, but for the user is can be rather confusing since they often ad the asteriks when doing an incomplete string search. 

Inventarisator: g de munck
de munck* = 0
de munck = 17
munck* = 17
munck  = 17
g de munck = 15 objecten
g de munck* = 0 objecten
*de*munck* = 0 objecten
*de munck*

Inventarisator: Dyck, Annemie Van
dyck* = 1153
dyck = 1153
Dyck, Annemie Van = 1153
Dyck, Annemie Van* = 0
Annemie Van* = 0
Annemie* = 1156
Annemie = 1156

**Comment by roxannewyns** [comment]
Field search works differently. When typing a part of a name, you get a suggestion o existing values. 

@naeemmuhammad  you can move this to production
