### ISSUE TITLE
activatie samenvatting voor collecties

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_crkc#52]
assigned @aruijmen 

Niet dringend, maar kan jij eens kijken of je samenvatting kan activeren voor collecties. Bij objecten staat dat er al. Ik denk dat het via de config files is, maar weet niet zeker meer. 

![capture](https://cloud.githubusercontent.com/assets/3798589/9518120/9d575b90-4cb4-11e5-8590-ae40e1c8c9ca.JPG)

**Comment by aruijmen** [comment]
Tabblad verschijnt, maar afdruk geeft leeg result.pdf document.
Zal ik verder bekijken.

**Comment by aruijmen** [comment]
Probleem opgelost.  Ook afdruk werkt nu. Geïmplementeerd op produktie
