### ISSUE TITLE
INDEXING: verschil tussen aantal records in front-end - back-end na herindexering

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_crkc#53]
search in database geeft andere resultaten dan in front-end na herindexering van afgelopen vrijdag. 
Ik heb in de database gezocht op alle records met deleted = 0. 
In de front-end met *

![capture](https://cloud.githubusercontent.com/assets/3798589/10574989/c81bd7ec-7659-11e5-9041-f21bb76c2323.JPG)

**Comment by naeemmuhammad** [comment]
Search related issues were mostly related with solr indexing, which is not being used any more.
