### ISSUE TITLE
balk onderaan terug op default afmeting zetten

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_crkc#57]
![capture](https://cloud.githubusercontent.com/assets/3798589/12919056/a247b490-cf42-11e5-9ea5-fd5ab58d6100.JPG)
Als ik me goed herinner hebben we deze balk onderaan ooit vergroot op vraag van CRKC om de leesbaarheid te verhogen. Het mogelijke gevolg is dat de onderste metadata soms niet leesbaar zijn door deze aanpassing.

**Comment by aruijmen** [comment]
Er werd voor gezord dat de laatste entry in de tabbladen navigatie aan de linkerkant niet achter de logout-balk schuift, door een kleine aanpassing aan de base.css
voor leftNavSidebar werd height = 90%
Dit is blijkbaar ook voor latere versies/onze andere klanten een probleem

**Comment by roxannewyns** [comment]
probleem blijft. op klein laptop scherm kan ik niet genoeg naar beneden scrollen

![capture](https://cloud.githubusercontent.com/assets/3798589/13140917/0a736afc-d635-11e5-9ecd-cf0445caa4f7.JPG)

**Comment by roxannewyns** [comment]
De scrollbalk van de tabbladen lijkt nu wel goed te werken. Er blijft wel een probleem met de werkbalk en de samenvatting. Het laatste veld "trefwoorden objectcategorie" staat deels bedekt door de balk.

![capture](https://cloud.githubusercontent.com/assets/3798589/13247984/6addc9d8-da1c-11e5-8810-03db4d2cb0bb.JPG)
