### ISSUE TITLE
INDEXING: Records still appear in search result after removing them from a collection

### ISSUE THREAD

**Issue by naeemmuhammad** [libis/ca_crkc#59]
In een objectrecord een relatie met een collectie legge. Bij zoeken op collectiecode bij objecten verschijnt het object correct in de resultatenlijst. Na het verwijderen van de relatie met de collectie blijft het object daarna echter in de resultaten verschijnen. 

Fix for this issue could be similar to fix for set issue (https://github.com/libis/ca_crkc/issues/12).

**Comment by roxannewyns** [comment]
Bij inloggen met een account behorende tot de gebruikersgroep vraag en aanbod, kreeg ik eerst 63 objecten te zien. Refreshen en opnieuw zoeken gaf geen effect. Op een bepaald ogenblik waren de records die er niet thuishoorde toch verdwenen na een nieuwe zoekopdracht. CRKC had zelf niets meer aangepast aan de records. Misschien wilt dit zeggen dat er een vertraging zit op de indexering?

**Comment by aruijmen** [comment]
Er waren blijkbaar een aantal objecten en collecties waarvan de info 'foutief' in Solr zat. 
De problemen met VA waren snel opgelost.  Maar voor de volgende tests door CRKC uitgevoerd werden juist de collecties (2000 en 216B) gebruikt die problemen gaven.  Ik heb ondertussen hopelijk de problemen met al deze collecties opgelost.  
Voor CRKC blijft de werkwijze dezelfde:
- als object uit collectie VA verwijderd moet worden, dan doen ze dat vanuit het object-scherm.
- na verwijderen van de collectie, als het object dan tot geen enkele collectie meer behoort, -> voeg dan de dummy-collectie toe (collectieveld is immers verplicht - anders krijgt men fout-melding bij het opslaan, wat weerom tot andere problemen kan leiden)
- verander bovendien nog 'iets' aan het titel veld
Sla dan pas het object-record op.
Als deze werkwijze gevolgd wordt, dan zouden de aantallen in VA moeten kloppen.

**Comment by roxannewyns** [comment]
geen melding meer van gekregen.
