### ISSUE TITLE
Digitool PID vervangen door Rosetta IE 

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_crkc#62]
Door een probleem met de resolver zijn sommige representations niet vindbaar 'not found' via de Digitool PID ondanks het feit dat er afgeleiden van bestaan. 
Het issue met de resolver is doorgegeven aan Mehmet, maar het is beter om alle PIDs te vervangen door de nieuwe IE.

@samalloing levert een lijst aan met de nieuwe IE nummers. 
@aruijmen kan rechtstreeks een update actie op de MySQL database uitvoeren

**Comment by aruijmen** [comment]
Done
