### ISSUE TITLE
sorteren op laatst gewijzigd

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_crkc#65]
Vraag om sorteren op 'laatst gewijzigd' toe te voegen aan sort lijst zoekresultaten. 
Kan dat? En waar dan. Ik heb al gezocht in de conf bestanden, maar kan het niet terugvinden. Zie ook issue ca_cag/issues/4

**Comment by naeemmuhammad** [comment]
This feature is not available, however it has been communicated to Collective Access for a possible inclusion in upcoming release.

Reference: http://www.collectiveaccess.org/support/forum/index.php?p=/discussion/297126/sorting-by-last-modified
