### ISSUE TITLE
lengte standaard metadataveld (preferred_labels) wijzigen

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_crkc#70]
De partner vraagt of het mogelijk is om de lengte van het standaard metadatavelden (preferred_labels) te wijzigen.  Het veld voor 'familienaam/organisatie' is nu beperkt tot 100 karakters, maar het komt voor dat de naam langer is. 

Mogelijk is dit ergens in de conf files aan te passen. Ik heb al eens gekeken en ik denk dat "bundle_types.conf" wel eens de juiste zou kunnen zijn. Bv. door onder preferred_label de parameter width toe te voegen.

**Comment by aruijmen** [comment]
Doorgevoerd.
Er is bovendien een aanpassing van 
app/models/ca_entity_labels.php regel 113 nodig.
Aanpassingen op github dienen nog te gebeuren.
