### ISSUE TITLE
PDF samenvatting afdrukken geeft failed download

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_crkc#71]
Als je de samenvatting wilt afdrukken, krijf je een failed download. Misschien kan Naeem hier naar kijken?

**Comment by aruijmen** [comment]
Analyze:
Oorzaak van het probleem was onvoldoende rechten in lib/fonts van 
/ca_crkc/app/lib/core/Parsers/dompdf.  
Bij het aanmaken van van de html/pdf wordt in deze dir een log.html gemaakt door de webserver (apache) welke hier geen rechten had. Gevolg een leeg bestand.

Aanpassing:
in hoger vermeldde directory met sudo volgend commando uitgevoerd:
chmod 1777 lib/fonts

Opmerking:
Moet dit ook niet opgenomen worden in het deployment script?? @naeemmuhammad

**Comment by naeemmuhammad** [comment]
Indeed we can put it in our deployment scripts for collective access to provide necessary permissions to the webserver. We will plan it in our next weekly meeting.

**Comment by naeemmuhammad** [comment]
I along with anita did tests on test environment to reproduce the same issue but it could not be reproduced. Pdf is being generated with the default permissions (given at the time of the deployment) of the lib/fonts. Therefore while investigating further we should look for other possibilities as well that might have caused this issue.

**Comment by roxannewyns** [comment]
This is fixed, so I close this issue unless something still needs to be done / put on gitbug?
