### ISSUE TITLE
dubbel value of zilvermerken

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_crkc#75]
Zilvermerken shows twice the same value in the summary overview. In the search results overview it is OK. Check if the display templates are ok/matching and what could cause this.
It's an objects_x_objects relationship field, so that might have to do with it. 

Display used = detailweergave 
/Summary/object_id/154444
/Summary/object_id/172428

![capture](https://cloud.githubusercontent.com/assets/3798589/17475390/19493a72-5d5b-11e6-8fcc-97e89d57595d.JPG)

**Comment by naeemmuhammad** [comment]
Selection of 'Show Hierarchy'/''Toon Hierarchie' option in display bundle solves this issue.

![display](https://cloud.githubusercontent.com/assets/3896702/17858830/8c565cca-6887-11e6-9ef9-1f48982729fe.JPG)
