### ISSUE TITLE
Object datum opmerking value cleanup

### ISSUE THREAD

**Issue by naeemmuhammad** [libis/ca_crkc#76]
In the field ca_objects.objectDatumInfo.objectDatumOpmerking there are often brackets , for example (lepeltje) and (zoutvat). These where imported from the previous database, but they mess up the display. These brackets should be removed.

**Comment by roxannewyns** [comment]
Info en lijst aangepaste records doorgegeven aan partner ter controle in test.

**Comment by naeemmuhammad** [comment]
Cleanup is done on production environment.
