### ISSUE TITLE
Datatype Storage location

### ISSUE THREAD

**Issue by naeemmuhammad** [libis/ca_crkc#78]
Storage location or bewaarlocatie missing in the selection list when creating a new metadata element.

**Comment by aruijmen** [comment]
Can you elaborate on this Naeem.  (screenshot .....)

**Comment by naeemmuhammad** [comment]
Apparently this list is generated from the attributes defined in the /app/conf/attribute_types.conf configuration file. Version 1.4 of Collective Access has no StorageLocations attribute defined in this configuration file. Subsequent versions do have. 
Storagelocation is missing in CRKC attribute_type file because it is version 1.4 (https://github.com/libis/ca_crkc/blob/master/app/conf/attribute_types.conf). Whereas Alamire has it because it is version 1.6 (https://github.com/libis/ca_alamire_16/blob/master/app/conf/attribute_types.conf).

Addition of StorageLocations requires new functionality to be implemented, for example implementing new class in '__CA_LIB_DIR__/ca/Attributes/Values/' and a couple of classes in '/app/models'.

**Comment by roxannewyns** [comment]
This only exists from version 1.6 onwards. Migration process to 1.6 is being investigated.
