### ISSUE TITLE
no longer possible to upload documents. 

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_crkc#80]
CRKC can't add documents. Before this was possible, but it seems a previous restriction is back. Can you check this please.

![capture](https://cloud.githubusercontent.com/assets/3798589/23405088/d9d89870-fdb8-11e6-82fd-7a07c97766a1.JPG)

![capture](https://cloud.githubusercontent.com/assets/3798589/23405061/a29c7f02-fdb8-11e6-966b-f7ecbde38800.JPG)

**Comment by naeemmuhammad** [comment]
Fixed. 
Collective Access needs a directory ‘workspace’ (in media/collectiveassess directory) for this particular category of uploads. This directory was missing. I have created it on production and test environments.
